Task 1

In [5]:
import pandas as pd
iris = pd.read_csv("/content/IRIS.csv")
print("--------")
print(iris.head(3))
print("--------")
print(type(iris))
print("--------")
print(iris.shape)

--------
   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
--------
<class 'pandas.core.frame.DataFrame'>
--------
(150, 5)


Task 2

In [6]:
import pandas as pd
iris = pd.read_csv("/content/IRIS.csv")
print(iris.keys())

print(iris.shape)

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')
(150, 5)


Task 3

In [7]:
import pandas as pd
iris = pd.read_csv("/content/IRIS.csv")

print(iris.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB
None


Task 4

In [12]:
import numpy as np
from scipy import sparse
eye = np.eye(4)
print(eye)
print('-------')
sparse_matrix = sparse.csr_matrix(eye)
print(sparse_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
-------
  (0, 0)	1.0
  (1, 1)	1.0
  (2, 2)	1.0
  (3, 3)	1.0


Task 5

In [29]:
import pandas as pd
iris = pd.read_csv("/content/IRIS.csv")
print(iris.describe())

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000


Task 6

In [33]:
import pandas as pd
iris = pd.read_csv("/content/IRIS.csv")
print('observations of each specis:')
print(iris['species'].value_counts())

observations of each specis:
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: species, dtype: int64


Task 7

In [32]:
import pandas as pd
iris = pd.read_csv("/content/IRIS.csv")

print('Before')
print(iris.head())
new_iris = iris.drop('sepal_length', axis=1)

print('After')
print(new_iris.head())


Before
   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa
After
   sepal_width  petal_length  petal_width      species
0          3.5           1.4          0.2  Iris-setosa
1          3.0           1.4          0.2  Iris-setosa
2          3.2           1.3          0.2  Iris-setosa
3          3.1           1.5          0.2  Iris-setosa
4          3.6           1.4          0.2  Iris-setosa
